GENERAL:
  seed: 2021
  log_path: ./logs
  model_name: 'Img2Gene'
  log_name: 'gse'

DATASET:
  type: 'gse'
  data_dir: '/home/wzhang/data/st/GSE240429_uni'
  model_name: 'uni_v1'  
  gene_type: 'mean'
  num_genes: 1000
  num_outputs: 250
  num_neighbors: 5
  radius: 224
  normalize: true
  cpm: false
  smooth: false
  

  num_path: 10  
  pathway_dir: '/home/wzhang/data/st/GSE240429_uni/pathway' 
  pathway_key: 'aucell_scores'  # pathway key in h5ad file

MODEL:
  name: Img2Gene 
  num_genes: 250
  emb_dim: 1024
  depth1: 1
  depth2: 2
  depth3: 2
  num_heads1: 8
  num_heads2: 16
  num_heads3: 16
  mlp_ratio1: 2
  mlp_ratio2: 2
  mlp_ratio3: 2
  dropout1: 0.15
  dropout2: 0.15
  dropout3: 0.15
  kernel_size: 3
  learning_rate: 0.0001

TRAINING:
  batch_size: 32
  num_epochs: 100
  num_k: 4
  early_stopping:
    monitor: R
    patience: 20
    mode: max
